name: iranian_pooshesh_agent_day
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.2.0
  camera: ^0.9.4+5
  chewie: ^1.2.2
  cupertino_icons: ^1.0.2
  digit_to_persian_word: ^2.0.0
  dio: ^4.0.5-beta1
  flutter_cache_manager: ^3.3.0
  flutter_map: ^0.14.0
  flutter_pdfview: ^1.2.1
  flutter_polygon: ^0.3.0+2
  flutter_svg: ^1.0.0
  flutter_staggered_grid_view: ^0.4.0
  fluttertoast: ^8.0.8
  get: ^4.6.1
  image_picker: ^0.8.4+4
  infinite_scroll_pagination: ^3.1.0
  intl: ^0.17.0
  ionicons: ^0.1.2
  latlong2: ^0.8.1
  location: ^4.3.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  retrofit_generator: ^3.0.0+2
  retrofit: ^3.0.0
  permission_handler: ^8.3.0
  pin_code_fields: ^7.3.0
  shared_preferences: ^2.0.11
  timer_count_down: ^2.2.1
  url_launcher: ^6.0.17
  path_provider: ^2.0.8
  percent_indicator: ^3.4.0
  persian_datetime_picker: ^2.4.0
  photo_view: ^0.13.0
  signature: ^5.0.0
  smooth_page_indicator: ^1.0.0+2
  scrollable_positioned_list: ^0.2.3
  video_player: ^2.2.19
  video_compress: ^3.1.0
  wakelock: ^0.6.1+2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.1.5
  flutter_gen_runner:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/deyLogo.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

  fonts:
    - family: iransans
      fonts:
        - asset: fonts/iransans_black.ttf
          weight: 900
        - asset: fonts/iransans_bold.ttf
          weight: 700
        - asset: fonts/iransans_light.ttf
          weight: 300
        - asset: fonts/iransans_meduim.ttf
          weight: 500
        - asset: fonts/iransans_ultralight.ttf
          weight: 100

    - family: lalezar
      fonts:
        - asset: fonts/lalezar.ttf

flutter_gen:
  integrations:
    flutter_svg: true